services:
  bot:
    image: chat_mix_bot
    build: ./bot/
    #command: python3 bot.py
    volumes:
      - ./bot:/chat_mix_bot/bot
      - ./logs:/chat_mix_bot/logs
      - ./db:/chat_mix_bot/db
    env_file: .env
    restart: always